import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import CustomLink from '@/UI/link';
import Link from 'next/link';
import Image from 'next/image';

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
});
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <header className="mt-2 flex justify-between items-center">
                    <Link href="/">
                        <Image
                            src="/imgs/vehicle-wheel.svg"
                            alt="logo"
                            width={70}
                            height={70}
                        />
                    </Link>
                    <nav>
                        <ul className="flex gap-10 font-bold text-[28px]">
                            <li>
                                <CustomLink href="/">Filter</CustomLink>
                            </li>
                            <li>
                                <CustomLink href="/car-selector">
                                    Result
                                </CustomLink>
                            </li>
                        </ul>
                    </nav>
                    <div className="flex gap-2">
                        <button>cart</button>
                        <button>menu</button>
                    </div>
                </header>

                {children}
            </body>
        </html>
    );
}
